http:
  routers:
    prowlarr:
      rule: "Host(`prowlarr.local`)"
      entryPoints:
        - websecure
      service: prowlarr
      tls: true
  services:
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.99.5:9696"
