version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - 7575:7575
    volumes:
      - ./config:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    environment:
      - TZ=Europe/Paris
