- name: Synchroniser les fichiers de configuration vers ce serveur de monitoring
  hosts: all
  gather_facts: yes

  vars:
    dest_base: /opt/monitoring/homelab-config/config

    services:
      traefik: /opt/traefik
      homarr: /opt/homarr
      adguard: /opt/adguardhome/conf
      immich: /opt/immich
      vaultwarden: /opt/vaultwarden
      jellyseer: /opt/jellyseer
      mealie: /opt/mealie
      grocy: /opt/grocy
      arrstack: /opt/appdata
      paperless: /opt/paperless
      prometheus: /opt/prometheus

    file_patterns:
      - "*.yml"
      - "*.yaml"
      - "*.toml"
      - "*.json"
      - ".env"
      - "*.ini"
      - "*.sh"

  pre_tasks:
    - name: Marquer les hôtes à ignorer si pas dans services
      set_fact:
        skip_host: true
      when: services[inventory_hostname] is not defined

  tasks:
    - name: Définir les variables du service
      set_fact:
        service_name: "{{ inventory_hostname }}"
        config_path: "{{ services[inventory_hostname] }}"
      when: not skip_host | default(false)

    - name: Vérifier que le dossier source existe
      stat:
        path: "{{ config_path }}"
      register: source_dir
      when: not skip_host | default(false)

    - name: Copier les fichiers de config dans un répertoire temporaire lisible
      become: true
      shell: |
        set -e
        export_dir="/home/ansible/backup_{{ service_name }}"
        echo "[DEBUG] Création du dossier $export_dir"
        mkdir -p "$export_dir"
        echo "[DEBUG] Dossier de config : {{ config_path }}"
        echo "[DEBUG] Fichiers matchés : {{ file_patterns | join(', ') }}"

        echo "[DEBUG] Lancement de la copie..."
        find {{ config_path }} -type f \( {% for ext in file_patterns %} -iname '{{ ext }}'{% if not loop.last %} -o {% endif %}{% endfor %} \) \
          -exec cp --parents {} "$export_dir" \;

        echo "[DEBUG] Correction des permissions"
        chown -R ansible:ansible "$export_dir"
        echo "[DEBUG] Terminé copie vers $export_dir"
      register: backup_cp_result
      when:
        - not skip_host | default(false)
        - source_dir.stat.exists

    - name: Vérifier la présence du répertoire backup
      become: true
      stat:
        path: "/home/ansible/backup_{{ service_name }}"
      register: backup_folder_check
      when:
        - not skip_host | default(false)

    - name: Afficher l'état du dossier backup
      debug:
        var: backup_folder_check
      when:
        - not skip_host | default(false)

    - name: DEBUG - Affichage sortie de la copie
      debug:
        var: backup_cp_result.stdout_lines
      when: backup_cp_result is defined

    - name: Créer une archive locale avec tar
      shell: |
        export_dir="/home/ansible/backup_{{ service_name }}"
        tmp_archive="/tmp/{{ service_name }}.tar.gz"
        if [ -d "$export_dir" ] && [ "$(ls -A $export_dir)" ]; then
          tar -czf "$tmp_archive" -C "$export_dir" .
          echo "Archive créée: $tmp_archive"
        else
          echo "Dossier vide ou inexistant: $export_dir"
        fi
      when: not skip_host | default(false)

    - name: Vérifier que l'archive a bien été créée
      stat:
        path: "/tmp/{{ service_name }}.tar.gz"
      register: archive_file
      when: not skip_host | default(false)

    - name: Créer le dossier final sur le serveur de monitoring
      delegate_to: localhost
      become: true
      file:
        path: "{{ dest_base }}/{{ service_name }}"
        state: directory
        mode: '0755'
      when:
        - not skip_host | default(false)
        - archive_file.stat.exists

    - name: Copier l'archive vers le serveur de monitoring
      fetch:
        src: "/tmp/{{ service_name }}.tar.gz"
        dest: "{{ dest_base }}/{{ service_name }}/"
        flat: yes
      when:
        - not skip_host | default(false)
        - archive_file.stat.exists

    - name: Extraire l'archive sur le serveur de monitoring
      delegate_to: localhost
      become: true
      unarchive:
        src: "{{ dest_base }}/{{ service_name }}/{{ service_name }}.tar.gz"
        dest: "{{ dest_base }}/{{ service_name }}"
        remote_src: true
      when:
        - not skip_host | default(false)
        - archive_file.stat.exists

    - name: Nettoyer les fichiers temporaires sur les hôtes distants
      become: true
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/{{ service_name }}.tar.gz"
        - "/home/ansible/backup_{{ service_name }}"
      when: not skip_host | default(false)

    - name: Nettoyer l'archive temporaire sur le serveur de monitoring
      delegate_to: localhost
      become: true
      file:
        path: "{{ dest_base }}/{{ service_name }}/{{ service_name }}.tar.gz"
        state: absent
      when:
        - not skip_host | default(false)
        - archive_file.stat.exists
